version: "3.9"

networks:
  backend-net:
    driver: bridge

services:
  db:
    image: diegodev34/postgres:1.0.0
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=sizebay
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres -c checkpoint_timeout=600
               -c max_wal_size=4096
               -c synchronous_commit=0
               -c full_page_writes=0
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

  api01:
    image: diegodev34/teste-backend:1.0.0
    container_name: api01
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=admin
      - DB_PASSWORD=123
      - DB_DATABASE=sizebay
      - DB_POOL_QUANTITY=123
      - SERVER_PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    image: diegodev34/teste-backend:1.0.0
    container_name: api02
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=admin
      - DB_PASSWORD=123
      - DB_DATABASE=sizebay
      - DB_POOL_QUANTITY=123
      - SERVER_PORT=3000
    ports:
      - "3002:3000"
    depends_on:
      - db
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  nginx:
    image: diegodev34/nginx:1.0.0
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
